POSTGRESQL_USERNAME: POSTGRES_USER
POSTGRESQL_PASSWORD: POSTGRES_PASSWORD
POSTGRESQL_HOST: localhost
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: docsDB

#server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

#email
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: douglasnyabasa400@gmail.com
EMAIL_PASSWORD: your_password
VERIFY_EMAIL_HOST: http://localhost:8085